name: demo_sound
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  flutter_sound: ^9.23.1
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  hive: ^2.2.3
  path_provider: ^2.1.3
  permission_handler: ^11.4.0
  file_picker: ^9.2.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  fluttertoast: ^8.2.12
  equatable: ^2.0.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  device_info_plus: ^11.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner: ^5.10.0
  flutter_flavorizr: ^2.1.5
  freezed: ^2.3.4
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sound.mp3
    - assets/sound2.mp3
    - assets/sound3.mp3
    - assets/sound4.mp3
dependency_overrides:
  intl: ^0.18.0